apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 862714032458.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googleclothes:d7cd7bfe53b06920fef83c7874da5286223888fe
        ports:
        - containerPort: 80
