apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 862714032458.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googleclothes:7002dd732aeca8a669e2b3bbe9673110f6da7c3c
        ports:
        - containerPort: 80
