apiVersion: apps/v1
kind: Deployment
metadata:
  name: electronics-deployment
  labels:
    app: electronics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: electronics
  template:
    metadata:
      labels:
        app: electronics
    spec:
      containers:
      - name: electronics
        image: 862714032458.dkr.ecr.us-west-2.amazonaws.com/shopping-site-electronics:c9460cf49bb01d43b589b707b565ed5cd82ee64d
        ports:
        - containerPort: 80
