apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  labels:
    app: main-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
      - name: main-frontend
        image: 862714032458.dkr.ecr.us-west-2.amazonaws.com/shopping-site-main:7002dd732aeca8a669e2b3bbe9673110f6da7c3c
        ports:
        - containerPort: 80

