apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 862714032458.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlemusic:c9460cf49bb01d43b589b707b565ed5cd82ee64d
        ports:
        - containerPort: 80
