apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 862714032458.dkr.ecr.us-west-2.amazonaws.com/shopping-site-googlepay:7002dd732aeca8a669e2b3bbe9673110f6da7c3c
        ports:
        - containerPort: 80
